name: Build macOS

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Swift version
        run: swift --version

      - name: List Xcode versions
        run: ls /Applications | grep Xcode

      - name: Force Xcode 16.2
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app

      - name: Checkout
        uses: actions/checkout@v4

      - name: Disable Xcode's macro validation (required to build a universal binary)
        run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES

      - name: Build
        run: swift build -c release --arch arm64 --arch x86_64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: swift-bundler
          path: ./.build/apple/Products/Release/swift-bundler
