name: Build Linux

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: swift:6.0.0
    
    steps:
      - name: Swift version
        run: swift --version

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: swift build

      - name: Install runtime dependencies
        run: sudo apt install -y patchelf

      - name: Test
        run: swift test
